apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: develop-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      annotations:
        proxy.istio.io/config: |
          proxyMetadata:
            ISTIO_META_DNS_CAPTURE: "true"
            ISTIO_META_DNS_AUTO_ALLOCATE: "true"
    spec:
      dnsPolicy: "Default"    # Critical change
      dnsConfig:
        nameservers:
          - "8.8.8.8"        # Google DNS
      containers:
        - name: backend
          image: us-central1-docker.pkg.dev/euphoric-oath-463913-c3/tododevops/tododevops-backend:22
          ports:
            - containerPort: 5000
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: connection-string


---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: develop-v1
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
