# backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: develop-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: us-central1-docker.pkg.dev/euphoric-oath-463913-c3/backend-repo/tododevops-backend:22 
        ports:
        - containerPort: 3001

---

# backend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: develop-v1
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: NodePort
